server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/ms-email
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  rabbitmq:
    addresses:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

broker:
  queue:
    email:
      name: default.email
