server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/ms-user
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  rabbitmq:
    addresses: cloudamqp-address

broker:
  queue:
    email:
      name: default.email